on: [push]

jobs:
    store_pr_metadata_job:
        runs-on: ubuntu-latest
        name: Store our PR metadata!
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: step1
              id: step1
              uses: ./
